# Generated by Django 2.1.2 on 2018-10-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181009_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder'),
        ),
    ]
